module Geomash
  class Constants
    COUNTRY_TGN_LOOKUP = {}
    COUNTRY_TGN_LOOKUP['United States'] = {:tgn_id=>7012149, :tgn_country_name=>'United States'}
    COUNTRY_TGN_LOOKUP['Canada'] = {:tgn_id=>7005685, :tgn_country_name=>'Canada'}
    COUNTRY_TGN_LOOKUP['France'] = {:tgn_id=>1000070, :tgn_country_name=>'France'}
    COUNTRY_TGN_LOOKUP['Vietnam'] = {:tgn_id=>1000145, :tgn_country_name=>'Viet Nam'}
    COUNTRY_TGN_LOOKUP['South Africa'] = {:tgn_id=>1000193, :tgn_country_name=>'South Africa'}
    COUNTRY_TGN_LOOKUP['Philippines'] = {:tgn_id=>1000135, :tgn_country_name=>'Pilipinas'}
    COUNTRY_TGN_LOOKUP['China'] = {:tgn_id=>1000111, :tgn_country_name=>'Zhongguo'}
    COUNTRY_TGN_LOOKUP['Japan'] = {:tgn_id=>1000120, :tgn_country_name=>'Nihon'}

    STATE_ABBR = {
        'AL' => 'Alabama',
        'AK' => 'Alaska',
        'AS' => 'America Samoa',
        'AZ' => 'Arizona',
        'AR' => 'Arkansas',
        'CA' => 'California',
        'CO' => 'Colorado',
        'CT' => 'Connecticut',
        'DE' => 'Delaware',
        'DC' => 'District of Columbia',
        'FM' => 'Micronesia1',
        'FL' => 'Florida',
        'GA' => 'Georgia',
        'GU' => 'Guam',
        'HI' => 'Hawaii',
        'ID' => 'Idaho',
        'IL' => 'Illinois',
        'IN' => 'Indiana',
        'IA' => 'Iowa',
        'KS' => 'Kansas',
        'KY' => 'Kentucky',
        'LA' => 'Louisiana',
        'ME' => 'Maine',
        'MH' => 'Islands1',
        'MD' => 'Maryland',
        'MA' => 'Massachusetts',
        'MI' => 'Michigan',
        'MN' => 'Minnesota',
        'MS' => 'Mississippi',
        'MO' => 'Missouri',
        'MT' => 'Montana',
        'NE' => 'Nebraska',
        'NV' => 'Nevada',
        'NH' => 'New Hampshire',
        'NJ' => 'New Jersey',
        'NM' => 'New Mexico',
        'NY' => 'New York',
        'NC' => 'North Carolina',
        'ND' => 'North Dakota',
        'OH' => 'Ohio',
        'OK' => 'Oklahoma',
        'OR' => 'Oregon',
        'PW' => 'Palau',
        'PA' => 'Pennsylvania',
        'PR' => 'Puerto Rico',
        'RI' => 'Rhode Island',
        'SC' => 'South Carolina',
        'SD' => 'South Dakota',
        'TN' => 'Tennessee',
        'TX' => 'Texas',
        'UT' => 'Utah',
        'VT' => 'Vermont',
        'VI' => 'Virgin Island',
        'VA' => 'Virginia',
        'WA' => 'Washington',
        'WV' => 'West Virginia',
        'WI' => 'Wisconsin',
        'WY' => 'Wyoming'
    }

    #Terms that drive geographic parsers mad...
    #Possibly check using QA against LCSH Subject topics that aren't geographical...
    JUNK_TERMS = [
        'Cranberries',
        'History',
        'Maps',
        'State Police',
        'Pictorial works.',
        /[nN]ation/,
        'Asia',
        '(Republic)',
        'Directories',
        'Biography',
        #Some date removal
        /[\d]+th [cC]entury,/
    ]


    STATE_TOWN_TGN_IDS =
        {:MA => [
            {:location_name => "Abington", :tgn_id => "2049291"},
            {:location_name => "Acton", :tgn_id => "7015054"},
            {:location_name => "Acushnet", :tgn_id => "2049300"},
            {:location_name => "North Adams", :tgn_id => "7014234"},
            {:location_name => "Adams", :tgn_id => "2049304"},
            {:location_name => "Agawam", :tgn_id => "2049310"},
            {:location_name => "Alford", :tgn_id => "2049314"},
            {:location_name => "Allston", :tgn_id => "1003950"},
            {:location_name => "Amesbury", :tgn_id => "2049316"},
            {:location_name => "Amherst", :tgn_id => "7013296"},
            {:location_name => "North Andover", :tgn_id => "7014236"},
            {:location_name => "Andover", :tgn_id => "7013301"},
            {:location_name => "Aquinnah", :tgn_id => "2049808"},
            {:location_name => "Arlington", :tgn_id => "7013320"},
            {:location_name => "Ashburnham", :tgn_id => "2049328"},
            {:location_name => "Ashby", :tgn_id => "2049329"},
            {:location_name => "Ashfield", :tgn_id => "2049331"},
            {:location_name => "Ashland", :tgn_id => "2049332"},
            {:location_name => "Athol", :tgn_id => "7020033"},
            {:location_name => "North Attleborough", :tgn_id => "2050251"},
            {:location_name => "North Attleboro", :tgn_id => "2050251"},
            {:location_name => "Attleboro", :tgn_id => "2049344"},
            {:location_name => "Auburndale", :tgn_id => "2050216"},
            {:location_name => "Auburn", :tgn_id => "2049349"},
            {:location_name => "Avon", :tgn_id => "2049358"},
            {:location_name => "Ayer", :tgn_id => "2049359"},
            {:location_name => "Babson Park", :tgn_id => "2050853"},
            {:location_name => "Back Bay", :tgn_id => "1004027"},
            {:location_name => "Barnstable", :tgn_id => "7014989"},
            {:location_name => "Barre", :tgn_id => "2049368"},
            {:location_name => "Bass River", :tgn_id => "2050679"},
            {:location_name => "Beacon Hill", :tgn_id => "7015000"},
            {:location_name => "Becket", :tgn_id => "2049376"},
            {:location_name => "New Bedford", :tgn_id => "7014196"},
            {:location_name => "Bedford", :tgn_id => "2049378"},
            {:location_name => "Belchertown", :tgn_id => "2049383"},
            {:location_name => "Bellingham", :tgn_id => "2049385"},
            {:location_name => "Belmont", :tgn_id => "7013377"},
            {:location_name => "Berkley", :tgn_id => "2049406"},
            {:location_name => "Berlin", :tgn_id => "2049409"},
            {:location_name => "Bernardston", :tgn_id => "2049410"},
            {:location_name => "Beverly", :tgn_id => "7013417"},
            {:location_name => "Billerica", :tgn_id => "2049421"},
            {:location_name => "Blackstone", :tgn_id => "2049422"},
            {:location_name => "Blandford", :tgn_id => "2049426"},
            {:location_name => "Bolton", :tgn_id => "2049429"},
            {:location_name => "East Boston", :tgn_id => "7015009"},
            {:location_name => "South Boston", :tgn_id => "7015007"},
            {:location_name => "Boston", :tgn_id => "7013445"},
            {:location_name => "Bourne", :tgn_id => "2049495"},
            {:location_name => "Boxborough", :tgn_id => "2049500"},
            {:location_name => "Boxford", :tgn_id => "2049501"},
            {:location_name => "West Boylston", :tgn_id => "2050876"},
            {:location_name => "Boylston", :tgn_id => "2049505"},
            {:location_name => "New Braintree", :tgn_id => "2050203"},
            {:location_name => "Braintree", :tgn_id => "2049507"},
            {:location_name => "Bradford", :tgn_id => "2049888"},
            {:location_name => "Brewster", :tgn_id => "7013452"},
            {:location_name => "East Bridgewater", :tgn_id => "7015082"},
            {:location_name => "West Bridgewater", :tgn_id => "2050877"},
            {:location_name => "Bridgewater", :tgn_id => "2049517"},
            {:location_name => "Brighton", :tgn_id => "1004167"},
            {:location_name => "Brimfield", :tgn_id => "2049519"},
            {:location_name => "Brockton", :tgn_id => "7013455"},
            {:location_name => "East Brookfield", :tgn_id => "2049698"},
            {:location_name => "North Brookfield", :tgn_id => "2050260"},
            {:location_name => "West Brookfield", :tgn_id => "2050882"},
            {:location_name => "Brookfield", :tgn_id => "2049525"},
            {:location_name => "Brookline", :tgn_id => "7013458"},
            {:location_name => "Buckland", :tgn_id => "2049538"},
            {:location_name => "Burlington", :tgn_id => "2049542"},
            {:location_name => "Buzzards Bay", :tgn_id => "2049546"},
            {:location_name => "Cambridge", :tgn_id => "7013527"},
            {:location_name => "Canton", :tgn_id => "2049559"},
            {:location_name => "Carlisle", :tgn_id => "2049564"},
            {:location_name => "Carver", :tgn_id => "2049565"},
            {:location_name => "Centerville", :tgn_id => "2049570"},
            {:location_name => "Charlemont", :tgn_id => "2049576"},
            {:location_name => "Charlestown", :tgn_id => "7015010"},
            {:location_name => "Charlton", :tgn_id => "2049577"},
            {:location_name => "Chatham", :tgn_id => "7013586"},
            {:location_name => "Chelmsford", :tgn_id => "7013588"},
            {:location_name => "Chelsea", :tgn_id => "7015012"},
            {:location_name => "Cheshire", :tgn_id => "2049591"},
            {:location_name => "Chesterfield", :tgn_id => "2049595"},
            {:location_name => "Chester", :tgn_id => "2049593"},
            {:location_name => "Chestnut Hill", :tgn_id => "7032056"},
            {:location_name => "Chicopee", :tgn_id => "2049596"},
            {:location_name => "Chilmark", :tgn_id => "7013601"},
            {:location_name => "Clinton", :tgn_id => "2049616"},
            {:location_name => "Cohasset", :tgn_id => "2049619"},
            {:location_name => "Colrain", :tgn_id => "2049625"},
            {:location_name => "Concord", :tgn_id => "7013646"},
            {:location_name => "Conway", :tgn_id => "2049630"},
            {:location_name => "Cummington", :tgn_id => "2049642"},
            {:location_name => "Dalton", :tgn_id => "2049645"},
            {:location_name => "Danvers", :tgn_id => "2049648"},
            {:location_name => "Dartmouth", :tgn_id => "2049654"},
            {:location_name => "Dedham", :tgn_id => "7013518"},
            {:location_name => "Deerfield", :tgn_id => "7013521"},
            {:location_name => "Dennis Port", :tgn_id => "2049668"},
            {:location_name => "Dennis", :tgn_id => "2049667"},
            {:location_name => "Devens", :tgn_id => "7022168"},
            {:location_name => "Dighton", :tgn_id => "2049669"},
            {:location_name => "Douglas", :tgn_id => "2049674"},
            {:location_name => "Dorchester", :tgn_id => "7013575"},
            {:location_name => "Dover", :tgn_id => "2049675"},
            {:location_name => "Dracut", :tgn_id => "2049676"},
            {:location_name => "Dudley", :tgn_id => "2049682"},
            {:location_name => "Dunstable", :tgn_id => "2049687"},
            {:location_name => "Duxbury", :tgn_id => "7013627"},
            {:location_name => "East Longmeadow", :tgn_id => "2049719"},
            {:location_name => "East Walpole", :tgn_id => "2049737"},
            {:location_name => "Easthampton", :tgn_id => "2049712"},
            {:location_name => "Eastham", :tgn_id => "2049711"},
            {:location_name => "Easton", :tgn_id => "2049724"},
            {:location_name => "Edgartown", :tgn_id => "2049741"},
            {:location_name => "Egremont Plain", :tgn_id => "2312102"},
            {:location_name => "North Egremont", :tgn_id => "2050281"},
            {:location_name => "South Egremont", :tgn_id => "2050634"},
            {:location_name => "Erving", :tgn_id => "2049751"},
            {:location_name => "Essex", :tgn_id => "2049752"},
            {:location_name => "Everett", :tgn_id => "2049753"},
            {:location_name => "Fairhaven", :tgn_id => "2049755"},
            {:location_name => "Fall River", :tgn_id => "7014164"},
            {:location_name => "Falmouth", :tgn_id => "2049768"},
            {:location_name => "Fitchburg", :tgn_id => "7013763"},
            {:location_name => "Florida", :tgn_id => "2049782"},
            {:location_name => "Foxborough", :tgn_id => "2049790"},
            {:location_name => "Framingham", :tgn_id => "7013936"},
            {:location_name => "Franklin", :tgn_id => "2049799"},
            {:location_name => "Freetown", :tgn_id => "2049336"},
            {:location_name => "Gardner", :tgn_id => "2049807"},
            {:location_name => "Gay Head", :tgn_id => "2049808"},
            {:location_name => "Georgetown", :tgn_id => "2049809"},
            {:location_name => "Gill", :tgn_id => "2349466"},
            {:location_name => "Gloucester", :tgn_id => "7014073"},
            {:location_name => "Goshen", :tgn_id => "2049834"},
            {:location_name => "Gosnold", :tgn_id => "2356954"},
            {:location_name => "Grafton", :tgn_id => "7014078"},
            {:location_name => "Granby", :tgn_id => "2049838"},
            {:location_name => "Granville", :tgn_id => "2049840"},
            {:location_name => "Great Barrington", :tgn_id => "2049843"},
            {:location_name => "Greenfield", :tgn_id => "7014134"},
            {:location_name => "Groton", :tgn_id => "2049856"},
            {:location_name => "Groveland", :tgn_id => "2049857"},
            {:location_name => "South Hadley", :tgn_id => "7014518"},
            {:location_name => "Hadley", :tgn_id => "2049858"},
            {:location_name => "Halifax", :tgn_id => "2049862"},
            {:location_name => "Hamilton", :tgn_id => "2049865"},
            {:location_name => "Hampden", :tgn_id => "2049866"},
            {:location_name => "Hancock", :tgn_id => "7013688"},
            {:location_name => "Hanover", :tgn_id => "2049868"},
            {:location_name => "Hanson", :tgn_id => "2049871"},
            {:location_name => "Hardwick", :tgn_id => "2049874"},
            {:location_name => "Harvard", :tgn_id => "7015083"},
            {:location_name => "Harwich", :tgn_id => "2049879"},
            {:location_name => "Hatfield", :tgn_id => "2049884"},
            {:location_name => "Haverhill", :tgn_id => "2049885"},
            {:location_name => "Hawley", :tgn_id => "2049892"},
            {:location_name => "Heath", :tgn_id => "2049895"},
            {:location_name => "Hingham", :tgn_id => "2049904"},
            {:location_name => "Hinsdale", :tgn_id => "2049909"},
            {:location_name => "Holbrook", :tgn_id => "2049911"},
            {:location_name => "Holden", :tgn_id => "2049914"},
            {:location_name => "Holland", :tgn_id => "2049915"},
            {:location_name => "Holliston", :tgn_id => "2049916"},
            {:location_name => "Holyoke", :tgn_id => "7013717"},
            {:location_name => "Hopedale", :tgn_id => "7013720"},
            {:location_name => "Hopkinton", :tgn_id => "2049941"},
            {:location_name => "Housatonic", :tgn_id => "2049945"},
            {:location_name => "Hubbardston", :tgn_id => "2049947"},
            {:location_name => "Hudson", :tgn_id => "2049950"},
            {:location_name => "Hull", :tgn_id => "2049951"},
            {:location_name => "Huntington", :tgn_id => "2049955"},
            {:location_name => "Hyannis", :tgn_id => "2049957"},
            {:location_name => "Hyde Park", :tgn_id => "7015004"},
            {:location_name => "Ipswich", :tgn_id => "2049964"},
            {:location_name => "Jamaica Plain", :tgn_id => "7015005"},
            {:location_name => "Kingston", :tgn_id => "2049971"},
            {:location_name => "Lakeville", :tgn_id => "2049981"},
            {:location_name => "Lancaster", :tgn_id => "2049989"},
            {:location_name => "Lanesborough", :tgn_id => "2049990"},
            {:location_name => "Lawrence", :tgn_id => "2049994"},
            {:location_name => "Lee", :tgn_id => "2049998"},
            {:location_name => "Leicester", :tgn_id => "2050001"},
            {:location_name => "Lenox", :tgn_id => "7016268"},
            {:location_name => "Leominster", :tgn_id => "2050006"},
            {:location_name => "Leverett", :tgn_id => "7015079"},
            {:location_name => "Lexington", :tgn_id => "7013888"},
            {:location_name => "Leyden", :tgn_id => "2446784"},
            {:location_name => "Lincoln", :tgn_id => "7013891"},
            {:location_name => "Littleton", :tgn_id => "2050022"},
            {:location_name => "Longmeadow", :tgn_id => "2050026"},
            {:location_name => "Lowell", :tgn_id => "7013975"},
            {:location_name => "Ludlow", :tgn_id => "7013977"},
            {:location_name => "Lunenburg", :tgn_id => "2050041"},
            {:location_name => "Lynnfield", :tgn_id => "2050046"},
            {:location_name => "Lynn", :tgn_id => "2050042"},
            {:location_name => "Magnolia", :tgn_id => "2049826"},
            {:location_name => "Malden", :tgn_id => "7013986"},
            {:location_name => "Manchester-by-the-Sea", :tgn_id => "2050062"},
            {:location_name => "Mansfield", :tgn_id => "2050071"},
            {:location_name => "Marblehead", :tgn_id => "7013997"},
            {:location_name => "Marion", :tgn_id => "2050076"},
            {:location_name => "New Marlborough", :tgn_id => "2050209"},
            {:location_name => "Marlborough", :tgn_id => "2050078"},
            {:location_name => "Marshfield", :tgn_id => "2050079"},
            {:location_name => "Mashpee", :tgn_id => "2050083"},
            {:location_name => "Mattapan", :tgn_id => "7015006"},
            {:location_name => "Mattapoisett", :tgn_id => "2050089"},
            {:location_name => "Maynard", :tgn_id => "2050092"},
            {:location_name => "Medfield", :tgn_id => "7014022"},
            {:location_name => "Medford", :tgn_id => "7014023"},
            {:location_name => "Medway", :tgn_id => "2050102"},
            {:location_name => "Melrose", :tgn_id => "2050105"},
            {:location_name => "Mendon", :tgn_id => "2050109"},
            {:location_name => "Menemsha", :tgn_id => "2050110"},
            {:location_name => "Merrimac", :tgn_id => "2050111"},
            {:location_name => "Methuen", :tgn_id => "2050114"},
            {:location_name => "Middleborough", :tgn_id => "2050120"},
            {:location_name => "Middlefield", :tgn_id => "2050121"},
            {:location_name => "Middleton", :tgn_id => "2050123"},
            {:location_name => "Milford", :tgn_id => "2050128"},
            {:location_name => "Millbury", :tgn_id => "2050133"},
            {:location_name => "Millis", :tgn_id => "2050137"},
            {:location_name => "Millville", :tgn_id => "2050142"},
            {:location_name => "Milton", :tgn_id => "7014069"},
            {:location_name => "Monson", :tgn_id => "2050157"},
            {:location_name => "Montague", :tgn_id => "2050158"},
            {:location_name => "Monterey", :tgn_id => "2050159"},
            {:location_name => "Montgomery", :tgn_id => "2050160"},
            {:location_name => "Mount Washington", :tgn_id => "2050167"},
            {:location_name => "Nahant", :tgn_id => "7014178"},
            {:location_name => "Nantucket", :tgn_id => "7014179"},
            {:location_name => "Natick", :tgn_id => "7014190"},
            {:location_name => "Needham", :tgn_id => "2050190"},
            {:location_name => "New Ashford", :tgn_id => "2050194"},
            {:location_name => "New Salem", :tgn_id => "2050210"},
            {:location_name => "New Seabury", :tgn_id => "2050211"},
            {:location_name => "Newburyport", :tgn_id => "7014220"},
            {:location_name => "West Newbury", :tgn_id => "2050913"},
            {:location_name => "Newbury", :tgn_id => "7014219"},
            {:location_name => "Newton", :tgn_id => "2050214"},
            {:location_name => "Norfolk", :tgn_id => "2050231"},
            {:location_name => "North End", :tgn_id => "2545160"},
            {:location_name => "North Reading", :tgn_id => "2050315"},
            {:location_name => "Northampton", :tgn_id => "7014242"},
            {:location_name => "Northborough", :tgn_id => "2050257"},
            {:location_name => "Northbridge", :tgn_id => "2050258"},
            {:location_name => "Northfield", :tgn_id => "2050286"},
            {:location_name => "Norton", :tgn_id => "7014245"},
            {:location_name => "Norwell", :tgn_id => "2050332"},
            {:location_name => "Norwood", :tgn_id => "2050333"},
            {:location_name => "Oak Bluffs", :tgn_id => "7014249"},
            {:location_name => "Oakham", :tgn_id => "2050347"},
            {:location_name => "Orange", :tgn_id => "2050360"},
            {:location_name => "Orleans", :tgn_id => "2050361"},
            {:location_name => "Otis", :tgn_id => "2050364"},
            {:location_name => "Oxford", :tgn_id => "2050367"},
            {:location_name => "Palmer", :tgn_id => "2050372"},
            {:location_name => "Paxton", :tgn_id => "2050374"},
            {:location_name => "Peabody", :tgn_id => "7014394"},
            {:location_name => "Pelham", :tgn_id => "2050382"},
            {:location_name => "Pembroke", :tgn_id => "2050383"},
            {:location_name => "Pepperell", :tgn_id => "2050384"},
            {:location_name => "Peru", :tgn_id => "2050386"},
            {:location_name => "Petersham", :tgn_id => "2050387"},
            {:location_name => "Phillipston", :tgn_id => "2050388"},
            {:location_name => "Pittsfield", :tgn_id => "7014416"},
            {:location_name => "Plainfield", :tgn_id => "2050417"},
            {:location_name => "Plainville", :tgn_id => "2050418"},
            {:location_name => "Plymouth", :tgn_id => "7014421"},
            {:location_name => "Plympton", :tgn_id => "2050427"},
            {:location_name => "Princeton", :tgn_id => "2050443"},
            {:location_name => "Provincetown", :tgn_id => "7015018"},
            {:location_name => "Quincy", :tgn_id => "7014307"},
            {:location_name => "Randolph", :tgn_id => "2050469"},
            {:location_name => "Raynham", :tgn_id => "2050472"},
            {:location_name => "Reading", :tgn_id => "7014313"},
            {:location_name => "Rehoboth", :tgn_id => "2050475"},
            {:location_name => "Revere", :tgn_id => "2050476"},
            {:location_name => "Richmond", :tgn_id => "2050487"},
            {:location_name => "Rochester", :tgn_id => "2050497"},
            {:location_name => "Rockland", :tgn_id => "2050501"},
            {:location_name => "Rockport", :tgn_id => "2050502"},
            {:location_name => "Roslindale", :tgn_id => "1005467"},
            {:location_name => "West Roxbury", :tgn_id => "7015008"},
            {:location_name => "Roxbury", :tgn_id => "7015002"},
            {:location_name => "Rowe", :tgn_id => "2050507"},
            {:location_name => "Rowley", :tgn_id => "2050508"},
            {:location_name => "Royalston", :tgn_id => "2050509"},
            {:location_name => "Russell", :tgn_id => "2050510"},
            {:location_name => "Rutland", :tgn_id => "2050512"},
            {:location_name => "Sagamore", :tgn_id => "2050514"},
            {:location_name => "Salem", :tgn_id => "7014447"},
            {:location_name => "Salisbury", :tgn_id => "2050528"},
            {:location_name => "Sandisfield", :tgn_id => "2050536"},
            {:location_name => "Sandwich", :tgn_id => "7014468"},
            {:location_name => "Saugus", :tgn_id => "2050540"},
            {:location_name => "Savoy", :tgn_id => "2050549"},
            {:location_name => "Scituate", :tgn_id => "2050550"},
            {:location_name => "Seekonk", :tgn_id => "2050559"},
            {:location_name => "Sharon", :tgn_id => "2050563"},
            {:location_name => "Sheffield", :tgn_id => "2050571"},
            {:location_name => "Shelburne", :tgn_id => "2050572"},
            {:location_name => "Sherborn", :tgn_id => "2050576"},
            {:location_name => "Shirley", :tgn_id => "2050579"},
            {:location_name => "Shrewsbury", :tgn_id => "2050583"},
            {:location_name => "Shutesbury", :tgn_id => "2050589"},
            {:location_name => "Somerset", :tgn_id => "2050597"},
            {:location_name => "Somerville", :tgn_id => "2050602"},
            {:location_name => "South End", :tgn_id => "2677860"},
            {:location_name => "Southampton", :tgn_id => "2050609"},
            {:location_name => "Southborough", :tgn_id => "2050615"},
            {:location_name => "Southbridge", :tgn_id => "2050617"},
            {:location_name => "Southwick", :tgn_id => "2050674"},
            {:location_name => "Spencer", :tgn_id => "2050680"},
            {:location_name => "West Springfield", :tgn_id => "2050928"},
            {:location_name => "Springfield", :tgn_id => "7014531"},
            {:location_name => "Sterling", :tgn_id => "2050698"},
            {:location_name => "West Stockbridge", :tgn_id => "2050932"},
            {:location_name => "Stockbridge", :tgn_id => "7014544"},
            {:location_name => "Stoneham", :tgn_id => "2050706"},
            {:location_name => "Stoughton", :tgn_id => "2050712"},
            {:location_name => "Stow", :tgn_id => "2050719"},
            {:location_name => "Sturbridge", :tgn_id => "7014553"},
            {:location_name => "Sudbury", :tgn_id => "2050723"},
            {:location_name => "Sunderland", :tgn_id => "2050725"},
            {:location_name => "Sutton", :tgn_id => "2050727"},
            {:location_name => "Swampscott", :tgn_id => "2050728"},
            {:location_name => "Swansea", :tgn_id => "2050729"},
            {:location_name => "Taunton", :tgn_id => "7014569"},
            {:location_name => "Templeton", :tgn_id => "2050746"},
            {:location_name => "Tewksbury", :tgn_id => "2050747"},
            {:location_name => "West Tisbury", :tgn_id => "2050935"},
            {:location_name => "Tolland", :tgn_id => "2050758"},
            {:location_name => "Topsfield", :tgn_id => "7014379"},
            {:location_name => "Townsend", :tgn_id => "2050764"},
            {:location_name => "Truro", :tgn_id => "2050766"},
            {:location_name => "Tyngsborough", :tgn_id => "2050772"},
            {:location_name => "Tyringham", :tgn_id => "2050773"},
            {:location_name => "Upton", :tgn_id => "2050775"},
            {:location_name => "Uxbridge", :tgn_id => "2050777"},
            {:location_name => "Vineyard Haven", :tgn_id => "2050781"},
            {:location_name => "Waban", :tgn_id => "2050226"},
            {:location_name => "Wakefield", :tgn_id => "2050785"},
            {:location_name => "Wales", :tgn_id => "2050790"},
            {:location_name => "Walpole", :tgn_id => "2050791"},
            {:location_name => "Waltham", :tgn_id => "7014579"},
            {:location_name => "Ware", :tgn_id => "2050814"},
            {:location_name => "Wareham", :tgn_id => "2050815"},
            {:location_name => "Warren", :tgn_id => "2050821"},
            {:location_name => "Warwick", :tgn_id => "2050824"},
            {:location_name => "Washington", :tgn_id => "2050825"},
            {:location_name => "Watertown", :tgn_id => "7014591"},
            {:location_name => "Wayland", :tgn_id => "2050839"},
            {:location_name => "Webster", :tgn_id => "2050841"},
            {:location_name => "Wellesley", :tgn_id => "7014604"},
            {:location_name => "Wellfleet", :tgn_id => "2050858"},
            {:location_name => "Wendell", :tgn_id => "2050862"},
            {:location_name => "Wenham", :tgn_id => "2050864"},
            {:location_name => "Westborough", :tgn_id => "2050874"},
            {:location_name => "Westfield", :tgn_id => "7014614"},
            {:location_name => "Westford", :tgn_id => "2050896"},
            {:location_name => "Westhampton", :tgn_id => "2050900"},
            {:location_name => "Westminster", :tgn_id => "7015084"},
            {:location_name => "Weston", :tgn_id => "7014617"},
            {:location_name => "Westport", :tgn_id => "2050924"},
            {:location_name => "Westwood", :tgn_id => "7016328"},
            {:location_name => "Weymouth", :tgn_id => "2050948"},
            {:location_name => "Whately", :tgn_id => "2050958"},
            {:location_name => "Whitman", :tgn_id => "2050968"},
            {:location_name => "Wilbraham", :tgn_id => "2050969"},
            {:location_name => "Williamsburg", :tgn_id => "2050971"},
            {:location_name => "Williamstown", :tgn_id => "7014630"},
            {:location_name => "Wilmington", :tgn_id => "2050977"},
            {:location_name => "Winchendon", :tgn_id => "7014634"},
            {:location_name => "Winchester", :tgn_id => "7014635"},
            {:location_name => "Windsor", :tgn_id => "2050987"},
            {:location_name => "Winthrop", :tgn_id => "2050990"},
            {:location_name => "Woburn", :tgn_id => "2051000"},
            {:location_name => "Woods Hole", :tgn_id => "2051007"},
            {:location_name => "Worcester", :tgn_id => "7014647"},
            {:location_name => "Worthington", :tgn_id => "2051048"},
            {:location_name => "Wrentham", :tgn_id => "2051050"},
            {:location_name => "Yarmouth", :tgn_id => "2051052"}
        ]}
  end
end
